global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "kafka-chans"
    static_configs:
      - targets: ["kafka-chans:8080"]
        labels:
          implementation: "channels"

  # - job_name: "kafka-mutex"
  #   static_configs:
  #     - targets: ["kafka-mutex:8080"]
  #       labels:
  #         implementation: "mutex"
